# -*- coding: utf-8 -*-
"""CHE2064L1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_tBPCMy6SMD6bHDV8yC6q62TZis1BSZk
"""

import numpy as np
from scipy.optimize import newton, root

def scalar_f(x):
  return x**2 - np.exp(x)*np.cos(x) + 1.2

newton(scalar_f, 1.5)

def vector_f(v):
  x,y,z = v
  return [x**2*y-z, 2*z*np.exp(x)-y-1, x*y*(1-1/z)+.25]

vec = [1, 1, 1]

vector_f(vec)

sol = root(vector_f, vec)

sol.x

v_list = [1., 2., 3.]
v_np_array = np.array(v_list)